#!/bin/bash
# ─────────────────────────────────────────────────────────────────────────
# install.sh — installs vorwatch to /usr/local/bin and walks through
# first-time config interactively.
#
# Usage:
#   sudo bash install.sh            interactive wizard (recommended)
#   sudo bash install.sh --defaults skip prompts, write example conf as-is
#
# What it does:
#   1. Copies ./bin/vorwatch to /usr/local/bin/vorwatch
#   2. Prompts for the settings that matter (data dir, cron interval,
#      IP reputation key, email notifications) and writes
#      /etc/vorwatch/vorwatch.conf from your answers
#   3. Installs log rotation
#   4. Offers to run `vorwatch baseline` + `vorwatch install` immediately
# ─────────────────────────────────────────────────────────────────────────
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MODE="${1:-wizard}"

if [ "$(id -u)" -ne 0 ]; then
  echo "Run with sudo: sudo bash install.sh" >&2
  exit 1
fi

install -m 755 "$SCRIPT_DIR/bin/vorwatch" /usr/local/bin/vorwatch
echo "[OK] Installed /usr/local/bin/vorwatch"

mkdir -p /etc/vorwatch

if [ -f /etc/vorwatch/vorwatch.conf ]; then
  echo "[OK] /etc/vorwatch/vorwatch.conf already exists."
  read -rp "    Overwrite it with a fresh setup? [y/N] " overwrite
  if [[ ! "$overwrite" =~ ^[Yy]$ ]]; then
    echo "[OK] Leaving existing config untouched."
    MODE="skip-conf"
  fi
fi

if [ "$MODE" = "--defaults" ]; then
  cp "$SCRIPT_DIR/vorwatch.conf.example" /etc/vorwatch/vorwatch.conf
  echo "[OK] Wrote /etc/vorwatch/vorwatch.conf from the example template (edit it by hand to change anything)"
elif [ "$MODE" != "skip-conf" ]; then
  echo
  echo "── Vorwatch setup ──────────────────────────────────────────"
  echo "Press Enter on any question to accept the default shown."
  echo

  read -rp "Data directory for baseline/alerts/state [/home/$SUDO_USER/vorwatch]: " ans
  VORWATCH_DIR="${ans:-/home/${SUDO_USER:-$USER}/vorwatch}"

  read -rp "Check interval, cron syntax [*/15 * * * *]: " ans
  VORWATCH_CRON_SCHEDULE="${ans:-*/15 * * * *}"

  read -rp "Threat blocklist URL [firehol level1, Enter to accept]: " ans
  VORWATCH_BLOCKLIST_URL="${ans:-https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/firehol_level1.netset}"

  echo
  echo "IP reputation scoring (AbuseIPDB) grades your top-5 nginx source"
  echo "IPs 1-5 for risk. Free tier: 1000 checks/day. Leave blank to skip"
  echo "(top-5 IPs will just show as 'unrated')."
  read -rp "AbuseIPDB API key [blank = skip]: " VORWATCH_ABUSEIPDB_KEY

  echo
  echo "Email notifications: urgent alerts (blocklist hits, file tampering,"
  echo "nginx attack patterns) send immediately; everything else lands in a"
  echo "scheduled digest."
  read -rp "Enable email notifications? [y/N] " email_on

  VORWATCH_EMAIL_TO=""
  VORWATCH_EMAIL_FROM=""
  VORWATCH_RESEND_API_KEY=""
  VORWATCH_EMAIL_FREQUENCY="monday"
  VORWATCH_EMAIL_URGENT_COOLDOWN_HOURS="4"

  if [[ "$email_on" =~ ^[Yy]$ ]]; then
    read -rp "  Recipient email(s), comma-separated: " VORWATCH_EMAIL_TO
    read -rp "  Resend API key (https://resend.com, free tier available): " VORWATCH_RESEND_API_KEY
    read -rp "  From address [Vorwatch <alerts@yourdomain.com>]: " ans
    VORWATCH_EMAIL_FROM="${ans:-Vorwatch <alerts@yourdomain.com>}"
    read -rp "  Digest frequency, daily or monday [monday]: " ans
    VORWATCH_EMAIL_FREQUENCY="${ans:-monday}"
    read -rp "  Hours between repeat urgent emails of the same type [4]: " ans
    VORWATCH_EMAIL_URGENT_COOLDOWN_HOURS="${ans:-4}"
    echo "  Note: the From address's domain must be verified in your Resend"
    echo "  account, or delivery will fail."
  fi

  {
    echo "# /etc/vorwatch/vorwatch.conf — generated by install.sh $(date '+%Y-%m-%d %H:%M:%S %Z')"
    echo "# Sourced directly by the vorwatch script — plain shell variable"
    echo "# assignments. Anything left unset falls back to built-in defaults."
    echo
    echo "VORWATCH_DIR=\"$VORWATCH_DIR\""
    echo "VORWATCH_BLOCKLIST_URL=\"$VORWATCH_BLOCKLIST_URL\""
    echo "VORWATCH_BLOCKLIST_AGE_MAX=86400"
    echo "VORWATCH_CRON_SCHEDULE=\"$VORWATCH_CRON_SCHEDULE\""
    if [ -n "$VORWATCH_ABUSEIPDB_KEY" ]; then
      echo
      echo "VORWATCH_ABUSEIPDB_KEY=\"$VORWATCH_ABUSEIPDB_KEY\""
    fi
    if [ -n "$VORWATCH_EMAIL_TO" ]; then
      echo
      echo "VORWATCH_EMAIL_TO=\"$VORWATCH_EMAIL_TO\""
      echo "VORWATCH_EMAIL_FROM=\"$VORWATCH_EMAIL_FROM\""
      echo "VORWATCH_RESEND_API_KEY=\"$VORWATCH_RESEND_API_KEY\""
      echo "VORWATCH_EMAIL_FREQUENCY=\"$VORWATCH_EMAIL_FREQUENCY\""
      echo "VORWATCH_EMAIL_URGENT_COOLDOWN_HOURS=$VORWATCH_EMAIL_URGENT_COOLDOWN_HOURS"
    fi
  } > /etc/vorwatch/vorwatch.conf

  chown "${SUDO_USER:-root}:${SUDO_USER:-root}" /etc/vorwatch/vorwatch.conf 2>/dev/null || true
  chmod 600 /etc/vorwatch/vorwatch.conf
  echo
  echo "[OK] Wrote /etc/vorwatch/vorwatch.conf (permissions 600, owner ${SUDO_USER:-root})"
fi

# Logrotate path must match whatever VORWATCH_DIR ended up in the conf
# file (default, wizard-chosen, or an existing conf we left untouched) --
# never assume any specific user's home directory.
LOGROTATE_DIR="${VORWATCH_DIR:-}"
if [ -z "$LOGROTATE_DIR" ] && [ -f /etc/vorwatch/vorwatch.conf ]; then
  LOGROTATE_DIR=$(grep '^VORWATCH_DIR=' /etc/vorwatch/vorwatch.conf | sed -E 's/^VORWATCH_DIR="?([^"]*)"?$/\1/')
fi
LOGROTATE_DIR="${LOGROTATE_DIR:-/home/${SUDO_USER:-$USER}/.vorwatch}"

cat > /etc/logrotate.d/vorwatch << ROTATE_EOF
# /etc/logrotate.d/vorwatch
# Rotates vorwatch's growing log files. seen-outbound-ips.txt and
# baseline.txt are deliberately NOT here -- they're state, not logs;
# seen-outbound-ips.txt self-prunes via TTL inside \`vorwatch check\`
# instead of being truncated on a schedule.
$LOGROTATE_DIR/alerts.log
$LOGROTATE_DIR/cron.log
{
    weekly
    rotate 8
    compress
    missingok
    notifempty
    copytruncate
}
ROTATE_EOF
chmod 644 /etc/logrotate.d/vorwatch
echo "[OK] Installed /etc/logrotate.d/vorwatch -> $LOGROTATE_DIR (weekly rotation, 8 weeks retained)"

if [ "$MODE" != "--defaults" ] && [ "$MODE" != "skip-conf" ]; then
  echo
  read -rp "Run 'vorwatch baseline' and 'vorwatch install' now? [Y/n] " finish
  if [[ ! "$finish" =~ ^[Nn]$ ]]; then
    su - "${SUDO_USER:-root}" -c "vorwatch baseline"
    su - "${SUDO_USER:-root}" -c "vorwatch install"
    echo
    echo "[OK] Setup complete. Try: vorwatch status"
    exit 0
  fi
fi

echo
echo "Next steps:"
echo "  vorwatch baseline     # capture known-good state"
echo "  vorwatch check        # run one detection pass"
echo "  vorwatch install      # wire up the cron job(s)"
echo "  vorwatch status       # confirm everything's live"
